### ISSUE TITLE
Create p5.js sketch

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Bizarro-Devin#1]
When the command is first run it should create `index.html` and `sketch.js`.

**Comment by dipamsen** [comment]
Should the extension itself create the workspace? This seems a bit too much, probably whats ideal is that the extension will start from an empty workspace, and it creates the two files. Out of which, `index.html` will totally be boilerplate code, whereas `sketch.js` will be empty (populated based on LLM/AI Agent).

**Comment by dipamsen** [comment]
Similarly, the "user"'s workspace (running besides the AI one) would also have the same html boilerplate and an empty JS file.

**Comment by shiffman** [comment]
Yes, I think you are right. And in fact the extension doesn't really need to set up the layout of the different files, I can always do that manually. It would need to pinpoint / understand the difference between my code and its code. I'm also unsure how to best manage running two local live previews? These are things I need to test / try out, open to ideas!

**Comment by dipamsen** [comment]
@shiffman if you are talking about the arrangement of different editors in the window (preview on top etc), then that is covered by #9 ! For your own code, you'd be using a different workspace, you can in fact open two live previews on two instances on VSCode, they will use a different port.

**Comment by shiffman** [comment]
> It would need to pinpoint / understand the difference between my code and its code.

I was thinking it would be able to read and comment on my code as well, so the extension should have the knowledge of both workspaces and be able to distinguish between them. But this is maybe a 2.0 feature, first I just need to get it to work on its own without an awareness of me.

**Comment by JuggernautJf** [comment]
#16 << i have done this here
