### ISSUE TITLE
Suggestions !== Issues  => You should add a discussions tab...

### ISSUE THREAD

**Issue by JuggernautJf** [CodingTrain/Bizarro-Devin#17]
![uihiwa](https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/996172bb-5ff8-4bb6-81d7-299bf6d6eedc)
![hdhsd](https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/d3fd1bff-8a60-45de-95c6-244a5b706b84)

**Comment by supercrafter100** [comment]
I (personally) think that for such small project. Its easier to just keep them together here than to split them up. For larger projects I'd agree with you that its better to split up suggestions to discussions to leave only actual issues in here but this is such a small project. Additionally most users really don't know about the discussions tab anyways. So they'll probably (if they have a suggestion) end up creating an issue anyways, as it's the only thing they know about.

**Comment by JuggernautJf** [comment]
ok 😊
