### ISSUE TITLE
interface elements

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Bizarro-Devin#18]
As I think about how I might like to use this in a live performance the following elements feel like they would be useful:

* Button to stop / start the AI agent
* Button to "mute" the AI agent (this could be the same thing, but maybe I might want to let the AI agent continue coding but cut its audio?)

**Comment by JuggernautJf** [comment]
<img src="https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/4c298c9d-e9ee-4d76-a5bc-4368a3d7a868"/>
reference => https://code.visualstudio.com/api/extension-capabilities/extending-workbench

**Comment by JuggernautJf** [comment]
if its a minimal 1 button that changes from "mute" to "unmute" and back, then "Status Bar Item" is preffered

**Comment by supercrafter100** [comment]
I ended up using [editor actions](https://code.visualstudio.com/api/references/contribution-points#menu-example) in my PR. These are small buttons attached to the editor that can run commands (not outlined in your picture). They're just a suggestion but I don't think we need anything more complicated. Still up to change though hence why the PR is a draft for now.

**Comment by JuggernautJf** [comment]
> I ended up using [editor actions](https://code.visualstudio.com/api/references/contribution-points#menu-example) in my PR. These are small buttons attached to the editor that can run commands (not outlined in your picture). They're just a suggestion but I don't think we need anything more complicated. Still up to change though hence why the PR is a draft for now.

well, the buttons should be 
***pause Agent***: pause writing and narrating
***mute Agent***: continue the writing and skip narrating \<i think it should be done from the ai endpoint to stop narration steps>,
***unpause and unmute***: \<tell ai endpoint to start giving narration steps then> resume writing (if it had stopped), start reading narration steps

**Comment by supercrafter100** [comment]
So essentially just replace my stop button with a mute/unmute one? Start agent would do the equivalent of unpause / unmute or start if it isn't doing anything. Pause agent would completely halt what it's doing and mute agent would only mute it.
