### ISSUE TITLE
Run code formatter

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Bizarro-Devin#3]
Run "format document" after some code has been added?

**Comment by dipamsen** [comment]
Found the bug - this code works for formatting the document

```js
    await vscode.commands.executeCommand('vscode.open', editor.document.uri);
    await vscode.commands.executeCommand('editor.action.formatDocument');
```

The first line sets the text editor to be the active tab. Previously, the formatDocument action was running on the preview window, which did not have any effect.

**Comment by michaelshmitty** [comment]
Looking at the stream I was thinking wouldn’t it make sense to save the document instead of formatting it, which would then automatically format it anyway? I.e. ride on that vscode “format on save” functionality? @shiffman
