### ISSUE TITLE
Need to Simplify Paths [right now it desn't work]

### ISSUE THREAD

**Issue by JuggernautJf** [CodingTrain/Bizarro-Devin#31]
![before](https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/541cf128-e4ae-49f5-8a5a-13601ae4bf86)
#### Imports are getting cryptic, so i thought to add to `jsconfig.json`:
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "Node16",
    "target": "ES2022",
    "checkJs": false /* Typecheck .js files. */,
    "allowJs": true,
    "lib": ["ES2022"],
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@lib/*": ["src/lib/*"],
      "@util/*": ["src/util/*"],
      "@commands/*": ["src/commands/*"],
      "@agent/*": ["src/lib/agent/*"]
    }
 },
  "exclude": ["node_modules"]
}
```
### then, the imports will look like:
![after](https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/391e489f-9024-4bbe-8674-f2304fff9022)
## **BUT** right now this doesn't work

**Comment by supercrafter100** [comment]
The config.js file has to manually be created. Using the contents of the example config.js

**Comment by JuggernautJf** [comment]
![image](https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/93af8d83-5233-4298-82cf-7c9b141204ad)
### ref: <https://www.npmjs.com/package/module-alias#usage>

**Comment by shiffman** [comment]
This is working for me with a manual `config.js` file, I think that's good enough for now. This is not a general purpose tool (yet) just something that needs to work on one single computer :)
