### ISSUE TITLE
Make the agent able to "sabotage" the editor / computer

### ISSUE THREAD

**Issue by supercrafter100** [CodingTrain/Bizarro-Devin#7]
Something like opening the p5.js documentation to try and mess with shiffman, insert random stuff in his editor. Just spitting out ideas here.

**Comment by shiffman** [comment]
Yes, this is a fun idea!

**Comment by shiffman** [comment]
Going to close some issues as this comes together for next weekend's show. We can re-open and add ideas and new things afterwards.
