### ISSUE TITLE
setup files overwrite existing ones?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Bizarro-Devin#72]
This is not high priority, but as I'm playing around with animator.js, it's easy to fall out of sync with what's in the workspace vs. the extension codebase. Would be nice for it not to fail if I run the "setup files" command and instead just overwrite what is there?

**Comment by supercrafter100** [comment]
This was done [here](https://github.com/CodingTrain/Bizarro-Devin/pull/71/files#diff-27750e96d62605b64085d5ec08e118cc43d63256e101876f4b9d55bb26c05b04R42-R44) but it might be better to just commit this directly to the main branch. It's such a small change.
